#!/usr/bin/env bash

set -euC -o pipefail

readonly VERSION_REGEX='v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?'

declare version="${1:-}"

if ! grep -Eqx "$VERSION_REGEX" <<< "$version"; then
  echo "Invalid version: '${version}'" >&2
  exit 1
fi

git tag "$version"
git push origin "$version"
